### PR TITLE
hop-node: GasBoost: Make sure maxFeePerGas is always higher than baseFeePerGas

### PR DESCRIPTION
**Pull request by miguelmota**
- Makes sure that baseFeePerGas is not greater than maxFeePerGas
  - if baseFeePerGas is greater than maxFeePerGas, then maxFeePerGas is baseFeePerGas*2
    - if new maxFeePerGas is greater than maxGasPrice, then maxFeePerGas is maxGasPrice

### CODE REVIEW

**Comment by shanefontaine** [comment]
@miguelmota is the case where `baseFeePerGas > maxGasPrice` handled? I'm thinking of the case where we have a 500 gwei max and `baseFee` is spiking to 500+.

**Comment by miguelmota** [comment]
@shanefontaine good point, PR has been updated to always clamp maxFeePerGas to maxGasPrice if it's over

**Comment by shanefontaine** [comment]
@miguelmota I think it looks good. One more clarification: does `getCurrentBaseFeePerGas()` return the `baseFee` if the chain supports 1559 and `gasPrice` if it does not?

**Comment by miguelmota** [comment]
@shanefontaine if the chain supports 1559 then `getCurrentBaseFeePerGas` will always return the `baseFeePerGas` and `getCurrentBaseFeePerGas` is only called if the transaction type is 1559 so there shouldn't be an instance where getCurrentBaseFeePerGas is called and the tx type is not 1559

**Review by shanefontaine — APPROVED** [review]
👍 LGTM

**Pull request merged**
